// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AQ.Ab8RN6KrmfSRifnUxdcfGP8KsdFaYvf9uPCiPxqf1wvM4Nr-9w',
    appId: '1:523807139910:web:7cb568c73d4b8156b4c247',
    messagingSenderId: '523807139910',
    projectId: 'physiq-5811f',
    authDomain: 'physiq-5811f.firebaseapp.com',
    storageBucket: 'physiq-5811f.firebasestorage.app',
    measurementId: 'G-27QNH13NLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC5rldWkKogvMnt5rCAZ2tWCKQZyoXY-g',
    appId: '1:523807139910:android:e611c6a06e9df5e0b4c247',
    messagingSenderId: '523807139910',
    projectId: 'physiq-5811f',
    storageBucket: 'physiq-5811f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXItE_govqL8JxFhaX40XKJXt97OFARIQ',
    appId: '1:523807139910:ios:a1f36f286faaf00ab4c247',
    messagingSenderId: '523807139910',
    projectId: 'physiq-5811f',
    storageBucket: 'physiq-5811f.firebasestorage.app',
    androidClientId: '523807139910-fu2uv508bdh7no32sqpuh00bq6ej2aq4.apps.googleusercontent.com',
    iosClientId: '523807139910-ioohd84ujjdl01nqqntsmr9f4cnk8bth.apps.googleusercontent.com',
    iosBundleId: 'com.example.physiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXItE_govqL8JxFhaX40XKJXt97OFARIQ',
    appId: '1:523807139910:ios:a1f36f286faaf00ab4c247',
    messagingSenderId: '523807139910',
    projectId: 'physiq-5811f',
    storageBucket: 'physiq-5811f.firebasestorage.app',
    androidClientId: '523807139910-fu2uv508bdh7no32sqpuh00bq6ej2aq4.apps.googleusercontent.com',
    iosClientId: '523807139910-ioohd84ujjdl01nqqntsmr9f4cnk8bth.apps.googleusercontent.com',
    iosBundleId: 'com.example.physiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AQ.Ab8RN6KrmfSRifnUxdcfGP8KsdFaYvf9uPCiPxqf1wvM4Nr-9w',
    appId: '1:523807139910:web:047ce8992e2f91c4b4c247',
    messagingSenderId: '523807139910',
    projectId: 'physiq-5811f',
    authDomain: 'physiq-5811f.firebaseapp.com',
    storageBucket: 'physiq-5811f.firebasestorage.app',
    measurementId: 'G-LY3DBY0WMW',
  );

}