class LeaderboardUser {
  final int rank;
  final String name;
  final String countryFlag;
  final int points;

  const LeaderboardUser({
    required this.rank,
    required this.name,
    required this.countryFlag,
    required this.points,
  });
}

class LeaderboardData {
  static const LeaderboardUser currentUser = LeaderboardUser(
    rank: 7,
    name: 'Rohit Singh',
    countryFlag: '🇮🇳',
    points: 2840,
  );

  static const LeaderboardUser topUser = LeaderboardUser(
    rank: 1,
    name: 'Amit Kumar',
    countryFlag: '🇮🇳',
    points: 5120,
  );

  static final List<LeaderboardUser> allUsers = [
    topUser,
    const LeaderboardUser(
      rank: 2,
      name: 'Paul Johnson',
      countryFlag: '🇺🇸',
      points: 4750,
    ),
    const LeaderboardUser(
      rank: 3,
      name: 'Ashish Patel',
      countryFlag: '🇮🇳',
      points: 4530,
    ),
    const LeaderboardUser(
      rank: 4,
      name: 'Vikram',
      countryFlag: '👤',
      points: 4400,
    ),
    const LeaderboardUser(
      rank: 5,
      name: 'Jessica Lee',
      countryFlag: '👤',
      points: 4380,
    ),
    // Gap for 6
    const LeaderboardUser(
      rank: 6,
      name: 'David Brown',
      countryFlag: '🇬🇧',
      points: 3100,
    ),
    currentUser,
    const LeaderboardUser(
      rank: 8,
      name: 'Deepak Sharma',
      countryFlag: '👤',
      points: 2840,
    ),
    const LeaderboardUser(
      rank: 9,
      name: 'Alyssa M.',
      countryFlag: '👤',
      points: 2870,
    ),
    const LeaderboardUser(
      rank: 10,
      name: 'Rahul Verma',
      countryFlag: '👤',
      points: 2820,
    ),
    const LeaderboardUser(
      rank: 11,
      name: 'Sarah K.',
      countryFlag: '👤',
      points: 2500,
    ),
    const LeaderboardUser(
      rank: 12,
      name: 'Akash Gupta',
      countryFlag: '👤',
      points: 2360,
    ),
    // ... generate more if needed visually, but list says "Total 100 dummy users"
    // I'll generate the rest programmatically or just add a few at the bottom to match the screenshot
    const LeaderboardUser(
      rank: 99,
      name: 'Aman Joshi',
      countryFlag: '🇮🇳',
      points: 1810,
    ),
    const LeaderboardUser(
      rank: 100,
      name: 'Ishaan S.',
      countryFlag: '🇮🇳',
      points: 1810,
    ),
  ];

  // Helper to get full list with generated dummy data filling the gaps
  static List<LeaderboardUser> getFullList() {
    List<LeaderboardUser> list = List.from(allUsers);

    final List<String> firstNames = [
      'James',
      'Mary',
      'Robert',
      'Patricia',
      'John',
      'Jennifer',
      'Michael',
      'Linda',
      'William',
      'Elizabeth',
      'David',
      'Barbara',
      'Richard',
      'Susan',
      'Joseph',
      'Jessica',
      'Thomas',
      'Sarah',
      'Charles',
      'Karen',
      'Christopher',
      'Nancy',
      'Daniel',
      'Lisa',
      'Matthew',
      'Betty',
      'Anthony',
      'Margaret',
      'Mark',
      'Sandra',
      'Donald',
      'Ashley',
      'Steven',
      'Kimberly',
      'Paul',
      'Emily',
      'Andrew',
      'Donna',
      'Joshua',
      'Michelle',
      'Kenneth',
      'Dorothy',
      'Kevin',
      'Carol',
      'Brian',
      'Amanda',
      'George',
      'Melissa',
      'Timothy',
      'Deborah',
      'Ronald',
      'Stephanie',
      'Edward',
      'Rebecca',
      'Jason',
      'Sharon',
      'Jeffrey',
      'Laura',
      'Ryan',
      'Cynthia',
      'Jacob',
      'Kathleen',
      'Gary',
      'Amy',
      'Nicholas',
      'Shirley',
      'Eric',
      'Angela',
      'Jonathan',
      'Helen',
      'Stephen',
      'Anna',
      'Larry',
      'Brenda',
      'Justin',
      'Pamela',
      'Scott',
      'Nicole',
      'Brandon',
      'Emma',
    ];

    final List<String> lastNames = [
      'Smith',
      'Johnson',
      'Williams',
      'Brown',
      'Jones',
      'Garcia',
      'Miller',
      'Davis',
      'Rodriguez',
      'Martinez',
      'Hernandez',
      'Lopez',
      'Gonzalez',
      'Wilson',
      'Anderson',
      'Thomas',
      'Taylor',
      'Moore',
      'Jackson',
      'Martin',
      'Lee',
      'Perez',
      'Thompson',
      'White',
      'Harris',
      'Sanchez',
      'Clark',
      'Ramirez',
      'Lewis',
      'Robinson',
      'Walker',
      'Young',
      'Allen',
      'King',
      'Wright',
      'Scott',
      'Torres',
      'Nguyen',
      'Hill',
      'Flores',
      'Green',
      'Adams',
      'Nelson',
      'Baker',
      'Hall',
      'Rivera',
      'Campbell',
      'Mitchell',
      'Carter',
      'Roberts',
      'Gomez',
      'Phillips',
      'Evans',
      'Turner',
      'Diaz',
      'Parker',
      'Cruz',
      'Edwards',
      'Collins',
      'Reyes',
      'Stewart',
      'Morris',
      'Morales',
      'Murphy',
      'Cook',
      'Rogers',
      'Gutierrez',
      'Ortiz',
      'Morgan',
      'Cooper',
      'Peterson',
      'Bailey',
      'Reed',
      'Kelly',
      'Howard',
      'Ramos',
      'Kim',
      'Cox',
      'Ward',
      'Richardson',
    ];

    for (int i = 13; i < 99; i++) {
      final firstName = firstNames[i % firstNames.length];
      final lastName = lastNames[(i * 3) % lastNames.length];
      list.add(
        LeaderboardUser(
          rank: i,
          name: '$firstName $lastName',
          countryFlag: '👤',
          points: 2300 - (i * 5), // decreasing points
        ),
      );
    }

    list.sort((a, b) => a.rank.compareTo(b.rank));
    return list;
  }
}
